const FORM_ENDPOINTS = [
  "https://ended-tech-venice-bread.trycloudflare.com/api/enquiry",
  "https://rxid.co.uk/api/bfng/enquiry"
];

function currency(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n||0)}
function updateCalc(){const missed=Number(document.getElementById('missedPerWeek')?.value||0);const avg=Number(document.getElementById('avgValue')?.value||0);const close=Number(document.getElementById('closeRate')?.value||0)/100;const recover=Number(document.getElementById('recoverableShare')?.value||0)/100;const monthly=missed*avg*close*recover*4.33;const out=document.getElementById('calcOutput');if(out)out.textContent=currency(monthly)+'/mo'}
['missedPerWeek','avgValue','closeRate','recoverableShare'].forEach(id=>document.addEventListener('input',e=>{if(e.target&&e.target.id===id)updateCalc()}));
document.addEventListener('DOMContentLoaded',updateCalc);

function formToPayload(form){const data=new FormData(form);const payload={};for(const [k,v] of data.entries()){payload[k]=v}payload.source_page=location.href;payload.submitted_at=new Date().toISOString();payload.service_interest=payload.service_interest||'Trade enquiry recovery audit';payload.consent=Boolean(data.get('consent'));return payload}
function mailtoFallback(payload){const to='enquiries@bfng.co.uk';const subject=encodeURIComponent('BFNG audit request - '+(payload.business_name||payload.name||'new enquiry'));const body=encodeURIComponent(Object.entries(payload).map(([k,v])=>`${k}: ${v}`).join('\n'));window.location.href=`mailto:${to}?subject=${subject}&body=${body}`}
async function postToEndpoints(payload){let lastError=null;for(const endpoint of FORM_ENDPOINTS){try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(res.ok)return await res.json().catch(()=>({ok:true})) ;lastError=new Error(`Endpoint ${endpoint} returned ${res.status}`)}catch(err){lastError=err}}throw lastError||new Error('No endpoint available')}
document.addEventListener('submit',async e=>{const form=e.target;if(!(form instanceof HTMLFormElement))return;if(form.id!=='leadForm'&&!form.classList.contains('onboarding-form'))return;e.preventDefault();const status=document.getElementById('formStatus')||form.querySelector('[role="status"]');const button=form.querySelector('button[type="submit"]');const payload=formToPayload(form);if(button)button.disabled=true;if(status)status.textContent='Sending...';try{await postToEndpoints(payload);if(status)status.textContent='Enquiry received. BFNG will contact you shortly.';form.reset()}catch(err){if(status)status.textContent='Automatic submission is unavailable. Opening email fallback.';mailtoFallback(payload)}finally{if(button)button.disabled=false}});
